[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # Fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.95
    accessibility = 0.95
    best-practices = 0.9
    seo = 0.9
    pwa = 0.9

  [[plugins.inputs.audits]]
    path=""
  [[plugins.inputs.audits]]
    path="blog"
    [plugins.inputs.audits.thresholds]
      pwa = 0.3 # Weird errors on Netlify. Will have to investigate.
  [[plugins.inputs.audits]]
    path="projects"
    [plugins.inputs.audits.thresholds]
      pwa = 0.3
  [[plugins.inputs.audits]]
    path="/blog/the-fastest-way-to-get-time-stamps-in-javascript"
    [plugins.inputs.audits.thresholds]
      pwa = 0.3

[[redirects]]
  from = "/3l-the-grat-collection-of-mixins-for-less-introduction"
  to = "/blog/3l-the-grat-collection-of-mixins-for-less-introduction"

[[redirects]]
  from = "/how-to-improve-seo-with-css"
  to = "/blog/how-to-improve-seo-with-css"

[[redirects]]
  from = "/transition-with-transform-cant-be-future-proof"
  to = "/blog/transition-with-transform-cant-be-future-proof"

[[redirects]]
  from = "/css-keyframes-animations-with-less"
  to = "/blog/css-keyframes-animations-with-less"

[[redirects]]
  from = "/the-great-idea-for-social-media-urls-thanks-to-google"
  to = "/blog/the-great-idea-for-social-media-urls-thanks-to-google"

[[redirects]]
  from = "/new-mixins-matching-behaviour-in-less-1-3-0"
  to = "/blog/new-mixins-matching-behaviour-in-less-1-3-0"

[[redirects]]
  from = "/improve-click-rate-of-links-with-visited-pseudo-class"
  to = "/blog/improve-click-rate-of-links-with-visited-pseudo-class"

[[redirects]]
  from = "/remember-about-vertical-media-queries"
  to = "/blog/remember-about-vertical-media-queries"

[[redirects]]
  from = "/make-a-layout-with-fluid-and-fixed-size-columns"
  to = "/blog/make-a-layout-with-fluid-and-fixed-size-columns"

[[redirects]]
  from = "/the-curtain-effect-with-css"
  to = "/blog/the-curtain-effect-with-css"

[[redirects]]
  from = "/unorthodox-ideas-for-ahover-effects"
  to = "/blog/unorthodox-ideas-for-ahover-effects"

[[redirects]]
  from = "/distribute-divs-images-equaly-line"
  to = "/blog/distribute-divs-images-equaly-line"

[[redirects]]
  from = "/why-you-should-make-your-own-mixins-collection-for-less-or-sass"
  to = "/blog/why-you-should-make-your-own-mixins-collection-for-less-or-sass"

[[redirects]]
  from = "/how-to-get-individual-dates-and-days-of-week-in-google-analytics"
  to = "/blog/how-to-get-individual-dates-and-days-of-week-in-google-analytics"

[[redirects]]
  from = "/the-fastest-way-to-get-time-stamps-in-javascript"
  to = "/blog/the-fastest-way-to-get-time-stamps-in-javascript"
