name: "Validate the code is Marvelous"
on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: "Install dependencies"
        run: npm ci
      - name: "Lint"
        run: npm run lint
      - name: "Test with coverage"
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: npm run test -- --coverage
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov
